# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('ID_Enfermedades', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Enfermedades', models.CharField(max_length=10, unique=True, verbose_name='Código de enfermedad')),
                ('Nombre_Enfermedad', models.CharField(max_length=200, verbose_name='Nombre de la enfermedad')),
            ],
            options={
                'verbose_name_plural': 'Enfermedades',
            },
        ),
    ]
