# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('raza', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('ID_Mascota', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Mascota', models.CharField(max_length=10, unique=True, verbose_name='Código de mascota')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('Nombre_Mascota', models.CharField(max_length=20, verbose_name='Nombre de la mascota')),
                ('ID_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente')),
                ('ID_Raza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raza.raza', verbose_name='Raza')),
            ],
            options={
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
