# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Cliente', models.CharField(max_length=10, unique=True, verbose_name='Código de clientes*')),
                ('Nombres', models.CharField(max_length=20, verbose_name='Nombres*')),
                ('Apellido1', models.CharField(max_length=20, verbose_name='Primer Apellido*')),
                ('Apellido2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo Apellido')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo*')),
                ('Telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('Direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
