# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('ID_TipoMascota', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_TipoMascota', models.CharField(max_length=10, unique=True, verbose_name='Código de tipo mascota')),
                ('Nombre_TipoMascota', models.CharField(max_length=200, verbose_name='Tipo de mascota')),
            ],
            options={
                'verbose_name_plural': 'Tipos de mascotas',
            },
        ),
    ]
