# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ID_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Proveedor', models.CharField(max_length=10, unique=True, verbose_name='Código de proveedor')),
                ('Nombres', models.CharField(max_length=20, verbose_name='Nombres')),
                ('Apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('Laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name_plural': 'Provedores',
            },
        ),
    ]
