# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('ID_Unidad_Medida', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Unidad_Medida', models.CharField(max_length=10, unique=True, verbose_name='Código de unidad medida')),
                ('Nombre_Unidad_Medida', models.CharField(max_length=40, verbose_name='Nombre de la unidad de medida')),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medidas',
            },
        ),
    ]
