# Generated by Django 4.2 on 2024-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadodeCita',
            fields=[
                ('ID_EstadoCita', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_EstadoCita', models.CharField(max_length=10, verbose_name='Código de estado de cita')),
                ('Estado_Cita', models.CharField(max_length=200, verbose_name='Estado de cita')),
            ],
            options={
                'verbose_name_plural': 'Estados de citas',
            },
        ),
    ]
